### ISSUE TITLE
Enlarge featured image dimensions for "sticky" posts

### ISSUE THREAD

**Issue by KillYourFM** [thunderbird/thunderblog#55]
Prior to version 1.0.15, the featured image shown for "sticky" blog posts (or or whichever post occupies the featured slot at https://blog.thunderbird.net) was larger. After the version bump, it appears to be significantly smaller (as illustrated in screenshot). 
<img width="1190" alt="Screenshot 2024-04-24 at 7 41 25 AM" src="https://github.com/thunderbird/thunderblog/assets/47599547/df2bf2f8-2810-4e0b-8269-5265d87dfa69">

It should be enlarge to occupy more of that empty space. Thank you!

**Comment by devmount** [comment]
Hi Jason, thank you for this report. Are you sure it was bigger before? It is sized with grid and normally has 2/5 of available width:

![thunderblog_feat_image](https://github.com/thunderbird/thunderblog/assets/5441654/c6095ddb-3bf9-490d-a377-ef15657ea3dc)

But since the title of that post is really long, how about the following:

- The title has full width on top of the rest
- meta infos and excerpt have 50% and preview image has 50% of space

Something like this:
![image](https://github.com/thunderbird/thunderblog/assets/5441654/c5b29941-fbc3-4fd3-b0d5-6f6131021d7c)


@micahilbery @MelissaAutumn What do you think?

**Comment by KillYourFM** [comment]
Aha, you're absolutely right @devmount! Confirmed that it _was_ my imagination by visiting [Wayback Machine](https://web.archive.org/web/20230306013014/https://blog.thunderbird.net/). I didn't realize it was responsively shrinking the image. Not my call, but I like your proposed changes to the title width and image dimensions. Thanks for all your work!

**Comment by micahilbery** [comment]
I do like letting the title extend to the full width of the container, especially with longer titles like this.

**Comment by devmount** [comment]
@KillYourFM Haha no worries, still a good catch since thumbs in landscape mode are indeed very small in the current layout.
@micahilbery Alright, I'll look into this
